# Pré-processamento 3 - Estrutura silábica e revisão ortográfica

## Carregando a base tratada

In [ ]:
import pandas as pd
from pathlib import Path

# carrega a última versão da base sem alterar o arquivo original
df = pd.read_excel(Path("Corpus_SANTOS_TONI_FDC_tratado_sem_repeticoes.xlsx"))
df.head()

## Verificação das estruturas silábicas

In [ ]:
# conta as estruturas silábicas mais frequentes
df['ESTSILABICA'].value_counts().head(20)

In [ ]:
# seleciona registros sem estrutura silábica válida
df_erros_silabicos = df[df['ESTSILABICA'] == 'erro']
df_erros_silabicos[
    ['PALAVRA', 'LEMA', 'CATMORF', 'ESTSILABICA', 'CATACENTUAL', 'FREQ']
].head(20)

In [ ]:
# remove registros sem estrutura silábica válida
df = df[df['ESTSILABICA'] != 'erro']
df.shape

## Verificação de possíveis erros ortográficos

In [ ]:
# localiza ocorrências que contêm a sequência 'voc'
df[df['PALAVRA'].str.contains('voc', case=False, na=False)][
    ['PALAVRA', 'LEMA', 'CATMORF', 'FREQ']
]

In [ ]:
# mostra somente as palavras exatamente iguais a 'vocé' e 'vocés'
df[df['PALAVRA'].isin(['vocé', 'vocés'])][
    ['PALAVRA', 'LEMA', 'CATMORF', 'TRANSCRICAO',
     'ACENTUACAO', 'ESTSILABICA', 'CATACENTUAL', 'FREQ']
]

## Remoção de palavras concatenadas e correção ortográfica

In [20]:
# palavras dos registros identificados como concatenações
# usamos o texto para preservar os registros corretos após salvar o Excel
palavras_concatenadas = [
    'voc\u00e9est\u00e1', 'quevoc\u00e9', 'ivoc\u00e9', 'voc\u00e9vai',
    'adiantavoc\u00e9', 'amelievoc\u00e9', 'aquivoc\u00e9', 'bolinhavoc\u00e9',
    'corvocurioso', 'ivoc\u00e9deixa', 'ivoc\u00e9n\u00e3o', 'olhavoc\u00e9',
    'ondevoc\u00e9', 'poxavoc\u00e9', 'voc\u00e9quer', 'vovoc\u00e9',
    'ondecad\u00e9', 'cad\u00e9irinha'
]

# remove somente os registros concatenados selecionados
df = df[~df['PALAVRA'].isin(palavras_concatenadas)]

# corrige somente as palavras completas identificadas
df['PALAVRA'] = df['PALAVRA'].replace({
    'voc\u00e9': 'voc\u00ea',
    'voc\u00e9s': 'voc\u00eas'
})

# corrige a grafia de 'cadé' para 'cadê'
df['PALAVRA'] = df['PALAVRA'].replace({'cad\u00e9': 'cad\u00ea'})
df['LEMA'] = df['LEMA'].replace({'cad\u00e9': 'cad\u00ea'})

df['LEMA'] = df['LEMA'].replace({
    'voc\u00e9': 'voc\u00ea',
    'voc\u00e9s': 'voc\u00eas'
})

# salva a versão atualizada sem alterar a base original
df.to_excel("Corpus_SANTOS_TONI_FDC_tratado_sem_repeticoes.xlsx", index=False)
df.shape

(10847, 8)

In [22]:
df[df['PALAVRA'].str.contains('cadé', case=False, na=False)][
    ['PALAVRA', 'LEMA', 'CATMORF', 'FREQ']
]

,PALAVRA,LEMA,CATMORF,FREQ
46,cadé,cadé,Verbo Principal Indicativo Presente Terceira P...,1432
2445,cadé,cadé,Nome Própio Pessoa,7
3614,ondecadé,ondecadé,Verbo Principal Indicativo Presente Terceira P...,4
4930,cadé,cadé,Verbo Principal Indicativo Presente Terceira P...,2
7126,cadé,cadé,Verbo Principal Indicativo Presente Terceira P...,1
7129,cadéirinha,cadéirinha,Nome Comun Feminino Singular,1

In [33]:
pd.set_option("display.max_rows", None)

possiveis_concatenadas[
    ["PALAVRA", "LEMA", "CATMORF", "FREQ"]
]

,PALAVRA,LEMA,CATMORF,FREQ
276,pequenininho,pequenininho,Nome Comun Masculino Singular,159
497,pequenininha,pequenininho,Nome Comun Feminino Singular,78
786,quebracabeça,quebracabeça,Nome Comun Feminino Singular,44
922,brancadeneve,brancadeneve,Nome Própio Pessoa,35
974,interessante,interessante,Adjetivo Qualificativo Comum Singular,33
1133,devagarzinho,devagarzinho,Nome Comun Masculino Singular,26
1191,brinquedinho,brinquedinho,Nome Própio Pessoa,24
1240,tiranossauro,tiranossauro,Nome Comun Masculino Singular,23
1985,brincadeirinha,brincadeira,Nome Comun Feminino Singular,10
2010,dinossaurinho,dinossaurinho,Nome Própio Pessoa,10
1984,brancadeneve,brancadeneve,Nome Própio Pessoa,10
2084,tchitchitchitchi,tchitchitchitchi,Interjeição,10
1974,atrapalhando,atrapalhar,Verbo Principal Gerúndio,10
2155,estreladomar,estreladomar,Nome Própio Organização,9
2117,brinquedoteca,brinquedoteca,Nome Própio Pessoa,9
2373,questionando,questionar,Verbo Principal Gerúndio,8
2305,estegossauro,estegossauro,Nome Comun Masculino Singular,8
2487,escondeesconde,escondeesconde,Verbo Principal Indicativo Presente Terceira P...,7
2517,investigação,investigação,Nome Comun Feminino Singular,7
2893,telontossauro,telontossauro,Nome Comun Masculino Singular,6
2671,brinquedinhos,brinquedinhos,Adjetivo Qualificativo Masculino Plural,6
2885,supermercado,supermercado,Nome Comun Masculino Singular,6
3198,pterodactilo,pterodactilo,Nome Comun Masculino Singular,5
3186,porcoespinho,porcoespinho,Nome Própio Pessoa,5
2946,backyardigans,backyardigans,Nome Própio Pessoa,5
2968,cachorroquente,cachorroquente,Adjetivo Qualificativo Comum Singular,5
3169,pequenininhas,pequenininho,Nome Comun Feminino Plural,5
3251,tiranossauro,tiranossauro,Nome Própio Pessoa,5
3751,tumtumtumtumtum,tumtumtumtumtum,Nome Comun Masculino Singular,4
3599,nhamnhamnham,nhamnhamnham,Interjeição,4
3351,brancadeneve,brancadeneve,Nome Própio Pessoa,4
3746,tricerápodesquevoa,tricerápodesquevoa,Verbo Principal Indicativo Presente Terceira P...,4
3661,preguiçossauro,preguiçossauro,Nome Comun Masculino Singular,4
3378,chapéuzinhovermelho,chapéuzinhovermelho,Nome Própio Pessoa,4
3377,chapeuzinhovermelho,chapeuzinhovermelho,Nome Própio Pessoa,4
3449,encantamento,encantamento,Nome Comun Masculino Singular,4
3547,lembrancinha,lembrancinha,Adjetivo Qualificativo Feminino Singular,4
3458,entrevistadora,entrevistador,Nome Comun Feminino Singular,4
3460,escondeesconde,escondeesconde,Verbo Principal Indicativo Presente Terceira P...,4
3650,piupiupiupiupiupiupiu,piupiupiupiupiupiupiu,Verbo Principal Indicativo Passado Terceira Pe...,4
3629,pedrinhonaágua,pedrinhonaágua,Nome Própio Pessoa,4
3634,pequenasereia,pequenasereia,Nome Própio Pessoa,4
4494,pteranodonte,pteranodonte,Nome Própio Pessoa,3
4546,segundafeira,segundafeira,Nome Comun Feminino Singular,3
4624,tridimensional,tridimensional,Adjetivo Qualificativo Comum Singular,3
4577,superpoderosas,superpoderosas,Adjetivo Qualificativo Feminino Plural,3
4599,tiranossaurinho,tiranossaurinho,Nome Própio Pessoa,3
3852,arquiospiteriquix,arquiospiteriquix,Nome Própio Pessoa,3
3923,brincadeiras,brincadeira,Nome Comun Feminino Plural,3
3964,carcarodontorossauro,carcarodontorossauro,Nome Comun Masculino Singular,3
3985,chasgossauro,chasgossauro,Nome Comun Masculino Singular,3
3998,ciamortirano,ciamortirano,Nome Comun Masculino Singular,3
4013,cocócocócocócocócocó,cocócocócocócocócocó,Nome Comun Feminino Singular,3
4239,impressionada,impressionar,Verbo Principal Particípio Singular Feminino,3
4240,impressionante,impressionante,Adjetivo Qualificativo Comum Singular,3
4249,inteligéncia,inteligéncia,Nome Comun Feminino Singular,3
4250,interrompendo,interromper,Verbo Principal Gerúndio,3
4302,listrossauro,listrossauro,Nome Comun Masculino Singular,3
4320,macarrãozinho,macarrão,Nome Comun Masculino Singular,3
4377,museudehistórianatural,museudehistórianatural,Nome Própio Lugar,3
4383,nhanhanhanha,nhanhanhanha,Interjeição,3
4410,orisquidocado,orisquidocado,Verbo Principal Particípio Singular Masculino,3
4424,paquirinossauro,paquirinossauro,Nome Comun Masculino Singular,3
4429,participants,participants,Nome Própio Organização,3
4447,pequenasereia,pequenasereia,Nome Própio Pessoa,3
4449,pequenininhos,pequenininho,Nome Comun Masculino Plural,3
4461,piperanodonte,piperanodonte,Nome Própio Pessoa,3
4293,lexissolissauro,lexissolissauro,Nome Comun Masculino Singular,3
4495,pterodáctilo,pterodáctilo,Nome Comun Masculino Singular,3
4655,velociraptor,velociraptor,Nome Comun Masculino Singular,3
4560,soldadinhodechumbo,soldadinhodechumbo,Nome Própio Pessoa,3
5530,investigator,investigator,Nome Comun Masculino Singular,2
6249,tricerapodes,tricerapodes,Nome Comun Masculino Plural,2
6250,tricerápodes,tricerápodes,Nome Comun Masculino Plural,2
4712,adamaeovagabundo,adamaeovagabundo,Nome Comun Masculino Singular,2
4731,ahistóriadoovoestranho,ahistóriadoovoestranho,Adjetivo Qualificativo Masculino Singular,2
4745,alfabetizada,alemie,Nome Comun Feminino Singular,2
4775,antecipadamente,ant,Nome Própio Pessoa,2
4837,backyardigan,backyardigan,Nome Própio Pessoa,2
4893,borboletinha,borboletinha,Verbo Principal Indicativo Imperfeito Terceira...,2
4908,brontossauro,brontossauro,Nome Comun Masculino Singular,2
4949,caranguejohermitão,caranguejohermitão,Nome Própio Pessoa,2
4955,carneirinhofelpudo,carneirinhofelpudo,Advérbio Geral,2
4970,casteloratimbum,casteloratimbum,Nome Comun Masculino Singular,2
5004,chuchuchuchu,chuchuchuchu,Nome Própio Pessoa,2
5051,completamente,completamente,Advérbio Geral,2
5087,coraçãozinho,coração,Nome Comun Masculino Singular,2
5137,departamento,departamento,Nome Comun Masculino Singular,2
5153,desenrolando,desenrolar,Verbo Principal Gerúndio,2
5199,dorminhocossauro,dorminhocossauro,Nome Comun Masculino Singular,2
5224,elefantezinho,elefante,Nome Comun Masculino Singular,2
5226,eletrodomésticos,eletrodomésticos,Adjetivo Qualificativo Masculino Plural,2
5244,endireitando,endireitar,Verbo Principal Gerúndio,2
5249,engatinhando,engatinhar,Verbo Principal Gerúndio,2
5261,envergonhada,envergonhar,Verbo Principal Particípio Singular Feminino,2
5273,escondidinha,escondido,Adjetivo Qualificativo Diminutivo Feminino Sin...,2
5274,escorregador,escorregador,Nome Comun Masculino Singular,2
5302,estáchorando,estáchorando,Verbo Principal Gerúndio,2
5303,estádormindo,estádormindo,Verbo Principal Gerúndio,2
5304,estadosunidos,estadosunidos,Nome Própio Lugar,2
5315,estremilique,estremilique,Nome Própio Lugar,2
5786,ornitorrinco,ornitorrinco,Nome Comun Masculino Singular,2
5455,grilofalante,grilofalante,Nome Própio Pessoa,2
5526,interessantes,interessante,Adjetivo Qualificativo Comum Plural,2
5889,piterodáctilo,piterodáctilo,Nome Comun Masculino Singular,2
6199,thcitchitchitchi,thcitchitchitchi,Nome Própio Pessoa,2
6184,tchutchutchu,tchutchutchu,Interjeição,2
6183,tchuquitchuquitchuqui,tchuquitchuquitchuqui,Interjeição,2
6179,tchitchitchi,tchitchitchi,Interjeição,2
6145,sombrancelhas,sombrancelhas,Nome Própio Pessoa,2
6144,sombrancelha,sombrancelha,Nome Própio Pessoa,2
6131,sinsalabinsalabinbinbin,sinsalabinsalabinbinbin,Nome Própio Pessoa,2
6127,simsalabimsalabimbimbim,simsalabimsalabimbimbim,Advérbio Geral,2
6103,segundafeira,segundafeira,Nome Comun Feminino Singular,2
6051,riodejaneiro,riodejaneiro,Nome Própio Pessoa,2
5981,quebracabeças,quebracabeças,Nome Comun Feminino Plural,2
5956,proprietário,proprietário,Nome Comun Masculino Singular,2
5904,pocotópocotópocotó,pocotópocotópocotó,Advérbio Geral,2
6245,travesseirinho,travesseiro,Nome Comun Masculino Singular,2
5893,piupiupiupiupiu,piupiupiupiupiu,Verbo Principal Indicativo Passado Terceira Pe...,2
5844,pequeniníssima,pequenino,Adjetivo Qualificativo Feminino Singular,2
5813,participantschi,participantschi,Nome Própio Organização,2
5812,participantes,participante,Nome Comun Comum Plural,2
5811,participando,participar,Verbo Principal Gerúndio,2
5804,papelhigiénico,papelhigiénico,Adjetivo Qualificativo Masculino Singular,2
5803,papapapapapapapapapapapa,papapapapapapapapapapapa,Nome Própio Pessoa,2
5787,orroorroorro,orroorroorro,Nome Própio Pessoa,2
6278,universidade,universidade,Nome Comun Feminino Singular,2
5775,ondeestáwolly,ondeestáwolly,Nome Própio Pessoa,2
5649,mariachiquinha,mariachiquinha,Adjetivo Qualificativo Feminino Singular,2
5636,mantanossera,mantanossera,Verbo Principal Indicativo Imperfeito Terceira...,2
5615,magnéticogiro,magnéticogiro,Nome Própio Pessoa,2
5614,maglarossauro,maglarossauro,Nome Comun Masculino Singular,2
5571,lancheirinha,lancheirinha,Nome Comun Feminino Singular,2
5569,lalalalalalalalala,lalalalalalalalala,Verbo Principal Indicativo Presente Terceira P...,2
5328,experimentar,experimentar,Verbo Principal Infinitivo,2
11404,viscondedesabugosa,viscondedesabugosa,Nome Própio Pessoa,1
6362,abuáabuáabuá,abuáabuáabuá,Verbo Principal Indicativo Presente Terceira P...,1
6549,amaréumpoema,amarelo,Nome Comun Masculino Singular,1
6571,americanizado,amendoim,Nome Comun Masculino Plural,1
6643,apresentação,apresentação,Nome Comun Feminino Singular,1
6644,apresentador,apresentador,Nome Comun Masculino Singular,1
6645,apresentadora,apresentador,Nome Comun Feminino Singular,1
6692,arranjaremos,arranjar,Verbo Principal Indicativo Futuro Primeira Pes...,1
6699,arrebentando,arrebentar,Verbo Principal Gerúndio,1
6703,arrumadinhas,arrumado,Adjetivo Qualificativo Diminutivo Feminino Plural,1
6704,arrumadinhos,arrumado,Adjetivo Qualificativo Diminutivo Masculino Pl...,1
6717,asferiasdabruxonilda,asferiasdabruxonilda,Nome Própio Pessoa,1
6739,astronómicas,astronómico,Adjetivo Qualificativo Feminino Plural,1
6745,atartarugaquequeriavoar,atartarugaquequeriavoar,Verbo Principal Infinitivo,1
6756,atravessasse,atravessar,Verbo Principal Subjuntivo Imperfeito Terceira...,1
6817,backyardgans,backyardgans,Nome Própio Pessoa,1
6830,balangandans,balangandans,Nome Própio Pessoa,1
6843,bandeirantes,bandeirantes,Nome Própio Organização,1
6862,barraquinhas,barraca,Nome Comun Feminino Plural,1
6865,barriguinhas,barriga,Nome Comun Feminino Plural,1
6883,beelelenocirco,beelelenocirco,Nome Própio Pessoa,1
6903,bepepilantra,bepepilantra,Verbo Principal Indicativo Presente Terceira P...,1
6922,bíbliadosanimais,bíbliadosanimais,Nome Própio Pessoa,1
6926,bichopreguiça,bichopreguiça,Nome Comun Feminino Singular,1
6930,bigtreinador,bigtreinador,Nome Própio Pessoa,1
6945,bleubleubleu,bleubleubleu,Verbo Principal Indicativo Passado Terceira Pe...,1
6947,blinblonblonblin,blinblonblonblin,Nome Própio Pessoa,1
6949,blindonblindon,blindonblindon,Nome Própio Pessoa,1
6953,blublublublu,blublublublu,Nome Própio Pessoa,1
6966,bolahistória,bolahistória,Nome Comun Feminino Singular,1
6986,bonecojoaquim,bonecojoaquim,Nome Própio Pessoa,1
7000,bonitinhoque,bonitinhoque,Nome Comun Masculino Singular,1
7027,brancadeneve,brancadeneve,Nome Própio Pessoa,1
7028,brancadeneve,brancadeneve,Nome Comun Feminino Singular,1
7029,brancadeneveeosseteanões,brancadeneveeosseteanões,Nome Própio Pessoa,1
7034,braquiossauro,braquiossauro,Nome Comun Masculino Singular,1
7035,brasileiríssima,brasileiro,Adjetivo Qualificativo Feminino Singular,1
7052,brincarcomigo,brincarcomigo,Nome Comun Masculino Singular,1
7054,brincarmamãe,brincarmamãe,Nome Comun Feminino Singular,1
7066,brumbrumbrumbrum,brumbrumbrumbrum,Nome Comun Masculino Singular,1
7073,bububububububu,bububububububu,Verbo Principal Indicativo Passado Terceira Pe...,1
7107,cabeleireira,cabeleireiro,Nome Comun Feminino Singular,1
7108,cabeleireiro,cabeleireiro,Nome Comun Masculino Singular,1
7122,cachoeirinha,cachoeirinha,Nome Comun Feminino Singular,1
7177,cantandobrincando,cantandobrincando,Verbo Principal Gerúndio,1
7192,característica,característica,Nome Comun Feminino Singular,1
7218,carrinhoestá,carrinhoestá,Verbo Principal Indicativo Presente Terceira P...,1
7268,celurossauro,celurossauro,Nome Comun Masculino Singular,1
7283,chacoalhadinha,chacoalhadinha,Nome Própio Pessoa,1
7300,chapeuzinhovermelho,chapeuzinhovermelho,Nome Própio Pessoa,1
7301,chapeuzinhovermelho,chapeuzinhovermelho,Nome Própio Pessoa,1
7315,chichichichichi,chichichichichi,Nome Própio Pessoa,1
7380,cliqueclique,cliqueclique,Nome Própio Lugar,1
7398,cócócócócócó,cócócócócócó,Nome Comun Feminino Singular,1
7414,coincidentes,coincidente,Adjetivo Qualificativo Comum Plural,1
7469,comocontarcrocodilos,comocontarcrocodilos,Nome Própio Organização,1
7479,complicadinho,complicadinho,Verbo Principal Particípio Singular Masculino,1
7503,confabulação,confabulação,Nome Comun Feminino Singular,1
7508,confortáveis,confortável,Adjetivo Qualificativo Comum Plural,1
7523,consentração,consentração,Nome Comun Feminino Singular,1
7559,conversandos,conversandos,Nome Própio Pessoa,1
7584,correcutianacasadatia,correcutianacasadatia,Nome Própio Pessoa,1
7588,corsalópolis,corsalópolis,Nome Própio Pessoa,1
7614,creamcracker,creamcracker,Nome Própio Pessoa,1
7639,cuidadíssimo,cuidado,Adjetivo Qualificativo Superlativo Masculino S...,1
7645,cuidocuidado,cuidocuidado,Nome Comun Masculino Singular,1
7650,cumpriiiiido,cumpriiiiido,Verbo Principal Particípio Singular Masculino,1
7666,cutecutecute,cutecutecute,Verbo Principal Indicativo Presente Terceira P...,1
7672,dadadadadadodododo,dadadadadadodododo,Nome Comun Masculino Singular,1
7695,definitivamente,definitivamente,Advérbio Geral,1
7726,desaparafusar,desaparafusar,Verbo Principal Infinitivo,1
7727,desaparecendo,desaparecer,Verbo Principal Gerúndio,1
7728,desapareceram,desaparecer,Verbo Principal Indicativo Passado Terceira Pe...,1
7735,descaradamente,descaradamente,Advérbio Geral,1
7736,descarregada,descarregado,Verbo Principal Particípio Singular Feminino,1
7737,descarreguei,descarregar,Verbo Principal Indicativo Passado Primeira Pe...,1
7747,desconfiança,desconfiança,Nome Comun Feminino Singular,1
7749,descongelado,descongelar,Verbo Principal Particípio Singular Masculino,1
7751,desconhecido,desconhecer,Verbo Principal Particípio Singular Masculino,1
7752,desconsolada,desconsolar,Verbo Principal Particípio Singular Feminino,1
7760,desdetrodonte,desdetrodonte,Nome Própio Pessoa,1
7768,desencaixado,desencaixar,Verbo Principal Particípio Singular Masculino,1
7773,desenganchou,desenganchar,Verbo Principal Indicativo Passado Terceira Pe...,1
7776,desenhozinho,desenho,Nome Comun Masculino Singular,1
7795,desobedecendo,desobedecer,Verbo Principal Gerúndio,1
7798,despedaçadinho,despedaçadinho,Verbo Principal Particípio Singular Masculino,1
7804,desprevenido,desprevenir,Verbo Principal Particípio Singular Masculino,1
7808,destrambelha,destrambelha,Nome Própio Pessoa,1
7822,devargazinho,devargazinho,Nome Comun Masculino Singular,1
7854,dinossaurinhos,dinossaurinhos,Nome Própio Pessoa,1
7874,distribuíndo,distribuíndo,Verbo Principal Gerúndio,1
7880,divagarzinho,divagarzinho,Nome Comun Masculino Singular,1
7892,documentação,documentação,Nome Comun Feminino Singular,1
7936,dragãomarinho,dragãomarinho,Nome Comun Masculino Singular,1
7994,elãmquepederme,elãmquepederme,Nome Própio Pessoa,1
7998,eletricidade,eletricidade,Nome Comun Feminino Singular,1
8000,eletrodoméstico,eletrodoméstico,Nome Comun Masculino Singular,1
8030,encantamentos,encantamento,Nome Comun Masculino Plural,1
8080,engraçadinho,engraçado,Nome Comun Masculino Singular,1
8110,entrevistador,entrevistador,Nome Comun Masculino Singular,1
8111,entrevistadora,entrevistador,Nome Comun Feminino Singular,1
8123,eosursinhostravessos,eosursinhostravessos,Nome Comun Masculino Plural,1
8128,equilibrista,equilibrista,Nome Comun Comum Singular,1
8136,esbugalhados,esbugalhar,Verbo Principal Particípio Plural Masculino,1
8152,escondidinhas,escondido,Adjetivo Qualificativo Diminutivo Feminino Plural,1
8153,escondidinho,escondido,Adjetivo Qualificativo Diminutivo Masculino Si...,1
8156,escorregando,escorregar,Verbo Principal Gerúndio,1
8157,escorregasse,escorregar,Verbo Principal Subjuntivo Imperfeito Terceira...,1
8186,espaçodavila,espaçodavila,Nome Própio Pessoa,1
8190,espalhafatoso,espalhafatoso,Adjetivo Qualificativo Masculino Singular,1
8200,espelhomágico,espelhomágico,Nome Própio Outros,1
8213,espinossauro,espinossauro,Nome Comun Masculino Singular,1
8217,espreguiçada,espreguiçar,Verbo Principal Particípio Singular Feminino,1
8223,esprimentando,esprimentando,Verbo Principal Gerúndio,1
8232,esquimozinha,esquimozinha,Nome Comun Feminino Singular,1
8242,estacionados,estacionar,Verbo Principal Particípio Plural Masculino,1
8244,estáconseguindo,estáconseguindo,Verbo Principal Gerúndio,1
8245,estadosunidos,estadosunidos,Nome Própio Lugar,1
8246,estadounidos,estadounidos,Nome Própio Lugar,1
8254,estáprocurando,estáprocurando,Verbo Principal Gerúndio,1
8269,estoufazendo,estoufazendo,Verbo Principal Gerúndio,1
8281,estreladomar,estreladomar,Nome Própio Organização,1
8320,experimentada,experimentar,Verbo Principal Particípio Singular Feminino,1
8321,experimentando,experimentar,Verbo Principal Gerúndio,1
8331,extremidades,extremidade,Nome Comun Feminino Plural,1
8378,fazercoceguinha,fazercoceguinha,Adjetivo Qualificativo Feminino Singular,1
8379,fazerdinossauro,fazerdinossauro,Nome Comun Masculino Singular,1
8426,ficarvendendo,ficarvendendo,Verbo Principal Gerúndio,1
8433,fiiiiiiuuuuuu,fiiiiiiuuuuuu,Verbo Principal Indicativo Passado Terceira Pe...,1
8499,formiguinhas,formiga,Nome Comun Feminino Plural,1
8509,fotografados,fotografar,Verbo Principal Particípio Plural Masculino,1
8510,fotografavam,fotografar,Verbo Principal Indicativo Imperfeito Terceira...,1
8560,galinhazinha,galinha,Nome Comun Feminino Singular,1
8615,giromagnético,giromagnético,Adjetivo Qualificativo Masculino Singular,1
8647,gragrandmother,gragrandmother,Nome Própio Outros,1
8659,grandparents,grandparents,Nome Própio Pessoa,1
8663,gravaçãozinha,gravação,Nome Comun Feminino Singular,1
8668,greatgrandmother,greatgrandmother,Nome Própio Outros,1
8691,guardachuvinha,guardachuvinha,Verbo Principal Indicativo Imperfeito Terceira...,1
8720,hahahahahaha,hahahahahaha,Nome Própio Pessoa,1
8748,hermanotauro,hermanotauro,Nome Comun Masculino Singular,1
8756,hipercansada,hipercansada,Verbo Principal Particípio Singular Feminino,1
8757,hipnotizando,hipnotizar,Verbo Principal Gerúndio,1
8781,horrorizadas,horrorizar,Verbo Principal Particípio Plural Feminino,1
8804,huuuuuuummmm,huuuuuuummmm,Nome Própio Pessoa,1
8835,iiiiiiiiiiriiioo,iiiiiiiiiiriiioo,Nome Própio Pessoa,1
8836,iiiiiiiiiriii,iiiiiiiiiriii,Nome Própio Pessoa,1
8841,ilhadosprazeres,ilhadosprazeres,Nome Comun Feminino Plural,1
8860,impressionou,impressionar,Verbo Principal Indicativo Passado Terceira Pe...,1
8862,improvisação,improvisação,Nome Comun Feminino Singular,1
8880,infelizmente,infelizmente,Advérbio Geral,1
8886,inhoqueinhoque,inhoqueinhoque,Nome Comun Masculino Singular,1
8890,insuportável,insuportável,Adjetivo Qualificativo Comum Singular,1
8891,inteligentésimo,inteligentésimo,Nome Própio Pessoa,1
8899,interpretação,interpretação,Nome Comun Feminino Singular,1
8903,interviewers,interviewers,Nome Própio Organização,1
8936,jabuticabeira,jabuticabeira,Nome Própio Pessoa,1
8998,justificações,justificação,Nome Comun Feminino Plural,1
9032,lalalalalalalalalala,lalalalalalalalalala,Verbo Principal Indicativo Presente Terceira P...,1
9048,landeossauro,landeossauro,Nome Comun Masculino Singular,1
9054,laranjapéramaçãeurso,laranjapéramaçãeurso,Nome Própio Pessoa,1
9149,livrodobichinho,livrodobichinho,Nome Própio Pessoa,1
9157,lobobonzinho,lobobonzinho,Nome Comun Masculino Singular,1
9159,lobomaudesmaiou,lobomaudesmaiou,Nome Própio Pessoa,1
9223,maçamaçamaça,maçamaçamaça,Nome Comun Feminino Singular,1
9225,macarrãodeletrinha,macarrãodeletrinha,Nome Comun Feminino Singular,1
9228,machadodeassis,machadodeassis,Nome Própio Lugar,1
9230,machucadinho,machucadinho,Verbo Principal Particípio Singular Masculino,1
9243,maglalossauro,maglalossauro,Nome Comun Masculino Singular,1
9246,magneticgiro,magneticgiro,Nome Própio Pessoa,1
9277,mamadeirinha,mamadeirinha,Nome Comun Feminino Singular,1
9280,mamãedamamãe,mamãedamamãe,Nome Comun Feminino Singular,1

In [35]:
indices_remover = [
    922, 1984, 2084, 2155, 3198, 2946, 3251, 3751, 3599, 3351,
    3746, 3661, 3378, 3377, 3650, 3629, 4494, 3852, 3964, 3985,
    3998, 1013, 4302, 4383, 4410, 4424, 4429, 4447, 4293, 4495,
    6249, 6250, 4731, 4837, 4908, 4970, 5004, 5199, 5526, 5889,
    6199, 6184, 6183, 6179, 6131, 6127, 5981, 5904, 5893, 5813,
    5803, 5787, 5775, 5649, 5636, 5615, 5614, 5571, 5569, 11404,
    6362, 6549, 6717, 6745, 6814, 6830, 6883, 6903, 6922, 6930,
    6945, 6947, 6949, 6953, 6966, 6983, 7000, 7027, 7028, 7029,
    7034, 7052, 7054, 7066, 7073, 7177, 7218, 7268, 7315, 7380,
    7398, 7469, 7503, 7559, 7584, 7588, 7614, 7645, 7650, 7666,
    7672, 7760, 7808, 7874, 7936, 7994, 8123, 8213, 8217, 8223,
    8232, 8281, 8379, 8426, 8433, 8560, 8615, 8647, 8659, 8663,
    8668, 8691, 8720, 8748, 8804, 8835, 8836, 8841, 8886, 8891,
    8903, 9032, 9048, 9054, 9149, 9157, 9159, 9223, 9225, 9228,
    9243, 9246, 9277, 9280, 9302, 3805, 9323, 9329, 9333, 9354,
    9396, 9419, 9447, 9518, 9573, 9574, 9625, 9629, 9630, 9687,
    9712, 9760, 9762, 10366, 9821, 9831, 9832, 9836, 9858, 9859,
    9927, 9931, 9950, 9955, 9974, 9975, 9976, 10000, 10020, 10032,
    10034, 10046, 10050, 10062, 10065, 10072, 10073, 10077, 10123,
    10127, 10140, 10174, 10199, 10251, 10255, 10257, 10265, 10287,
    10928, 10299, 10341, 10346, 10361, 10971, 10976, 10977, 10981,
    10992, 9776, 11053, 11054, 11055, 11064, 11084, 11130, 11131,
    11132
]

# Remove índices repetidos e que realmente existem no DataFrame
indices_remover = list(set(indices_remover))
indices_existentes = df.index.intersection(indices_remover)

print("Índices encontrados:", len(indices_existentes))
print("Índices não encontrados:",
      len(set(indices_remover) - set(indices_existentes)))

df = df.drop(index=indices_existentes).copy()

print("Novo tamanho da base:", df.shape)

Índices encontrados: 0
Índices não encontrados: 217
Novo tamanho da base: (10630, 8)

In [38]:
possiveis_concatenadas = df[
    df["PALAVRA"].str.len() >= 12
].sort_values(by="FREQ", ascending=False)

In [39]:
pd.set_option("display.max_rows", None)

possiveis_concatenadas[
    ["PALAVRA", "LEMA", "CATMORF", "FREQ"]
]

,PALAVRA,LEMA,CATMORF,FREQ
276,pequenininho,pequenininho,Nome Comun Masculino Singular,159
497,pequenininha,pequenininho,Nome Comun Feminino Singular,78
786,quebracabeça,quebracabeça,Nome Comun Feminino Singular,44
974,interessante,interessante,Adjetivo Qualificativo Comum Singular,33
1133,devagarzinho,devagarzinho,Nome Comun Masculino Singular,26
1191,brinquedinho,brinquedinho,Nome Própio Pessoa,24
1240,tiranossauro,tiranossauro,Nome Comun Masculino Singular,23
1985,brincadeirinha,brincadeira,Nome Comun Feminino Singular,10
1974,atrapalhando,atrapalhar,Verbo Principal Gerúndio,10
2010,dinossaurinho,dinossaurinho,Nome Própio Pessoa,10
2117,brinquedoteca,brinquedoteca,Nome Própio Pessoa,9
2373,questionando,questionar,Verbo Principal Gerúndio,8
2305,estegossauro,estegossauro,Nome Comun Masculino Singular,8
2517,investigação,investigação,Nome Comun Feminino Singular,7
2487,escondeesconde,escondeesconde,Verbo Principal Indicativo Presente Terceira P...,7
2885,supermercado,supermercado,Nome Comun Masculino Singular,6
2671,brinquedinhos,brinquedinhos,Adjetivo Qualificativo Masculino Plural,6
2893,telontossauro,telontossauro,Nome Comun Masculino Singular,6
2968,cachorroquente,cachorroquente,Adjetivo Qualificativo Comum Singular,5
3186,porcoespinho,porcoespinho,Nome Própio Pessoa,5
3169,pequenininhas,pequenininho,Nome Comun Feminino Plural,5
3449,encantamento,encantamento,Nome Comun Masculino Singular,4
3547,lembrancinha,lembrancinha,Adjetivo Qualificativo Feminino Singular,4
3458,entrevistadora,entrevistador,Nome Comun Feminino Singular,4
3460,escondeesconde,escondeesconde,Verbo Principal Indicativo Presente Terceira P...,4
3634,pequenasereia,pequenasereia,Nome Própio Pessoa,4
4546,segundafeira,segundafeira,Nome Comun Feminino Singular,3
4624,tridimensional,tridimensional,Adjetivo Qualificativo Comum Singular,3
4577,superpoderosas,superpoderosas,Adjetivo Qualificativo Feminino Plural,3
4599,tiranossaurinho,tiranossaurinho,Nome Própio Pessoa,3
3923,brincadeiras,brincadeira,Nome Comun Feminino Plural,3
4013,cocócocócocócocócocó,cocócocócocócocócocó,Nome Comun Feminino Singular,3
4239,impressionada,impressionar,Verbo Principal Particípio Singular Feminino,3
4240,impressionante,impressionante,Adjetivo Qualificativo Comum Singular,3
4249,inteligéncia,inteligéncia,Nome Comun Feminino Singular,3
4250,interrompendo,interromper,Verbo Principal Gerúndio,3
4320,macarrãozinho,macarrão,Nome Comun Masculino Singular,3
4377,museudehistórianatural,museudehistórianatural,Nome Própio Lugar,3
4449,pequenininhos,pequenininho,Nome Comun Masculino Plural,3
4461,piperanodonte,piperanodonte,Nome Própio Pessoa,3
4655,velociraptor,velociraptor,Nome Comun Masculino Singular,3
4560,soldadinhodechumbo,soldadinhodechumbo,Nome Própio Pessoa,3
6245,travesseirinho,travesseiro,Nome Comun Masculino Singular,2
4712,adamaeovagabundo,adamaeovagabundo,Nome Comun Masculino Singular,2
4745,alfabetizada,alemie,Nome Comun Feminino Singular,2
4775,antecipadamente,ant,Nome Própio Pessoa,2
4893,borboletinha,borboletinha,Verbo Principal Indicativo Imperfeito Terceira...,2
4949,caranguejohermitão,caranguejohermitão,Nome Própio Pessoa,2
4955,carneirinhofelpudo,carneirinhofelpudo,Advérbio Geral,2
5051,completamente,completamente,Advérbio Geral,2
5087,coraçãozinho,coração,Nome Comun Masculino Singular,2
5137,departamento,departamento,Nome Comun Masculino Singular,2
5153,desenrolando,desenrolar,Verbo Principal Gerúndio,2
5224,elefantezinho,elefante,Nome Comun Masculino Singular,2
5226,eletrodomésticos,eletrodomésticos,Adjetivo Qualificativo Masculino Plural,2
5244,endireitando,endireitar,Verbo Principal Gerúndio,2
5249,engatinhando,engatinhar,Verbo Principal Gerúndio,2
5261,envergonhada,envergonhar,Verbo Principal Particípio Singular Feminino,2
5273,escondidinha,escondido,Adjetivo Qualificativo Diminutivo Feminino Sin...,2
5274,escorregador,escorregador,Nome Comun Masculino Singular,2
5302,estáchorando,estáchorando,Verbo Principal Gerúndio,2
5303,estádormindo,estádormindo,Verbo Principal Gerúndio,2
5304,estadosunidos,estadosunidos,Nome Própio Lugar,2
5315,estremilique,estremilique,Nome Própio Lugar,2
5328,experimentar,experimentar,Verbo Principal Infinitivo,2
5455,grilofalante,grilofalante,Nome Própio Pessoa,2
5530,investigator,investigator,Nome Comun Masculino Singular,2
5786,ornitorrinco,ornitorrinco,Nome Comun Masculino Singular,2
5804,papelhigiénico,papelhigiénico,Adjetivo Qualificativo Masculino Singular,2
5811,participando,participar,Verbo Principal Gerúndio,2
5812,participantes,participante,Nome Comun Comum Plural,2
5844,pequeniníssima,pequenino,Adjetivo Qualificativo Feminino Singular,2
5956,proprietário,proprietário,Nome Comun Masculino Singular,2
6051,riodejaneiro,riodejaneiro,Nome Própio Pessoa,2
6103,segundafeira,segundafeira,Nome Comun Feminino Singular,2
6144,sombrancelha,sombrancelha,Nome Própio Pessoa,2
6145,sombrancelhas,sombrancelhas,Nome Própio Pessoa,2
6278,universidade,universidade,Nome Comun Feminino Singular,2
6571,americanizado,amendoim,Nome Comun Masculino Plural,1
6643,apresentação,apresentação,Nome Comun Feminino Singular,1
6644,apresentador,apresentador,Nome Comun Masculino Singular,1
6645,apresentadora,apresentador,Nome Comun Feminino Singular,1
6692,arranjaremos,arranjar,Verbo Principal Indicativo Futuro Primeira Pes...,1
6699,arrebentando,arrebentar,Verbo Principal Gerúndio,1
6703,arrumadinhas,arrumado,Adjetivo Qualificativo Diminutivo Feminino Plural,1
6704,arrumadinhos,arrumado,Adjetivo Qualificativo Diminutivo Masculino Pl...,1
6739,astronómicas,astronómico,Adjetivo Qualificativo Feminino Plural,1
6756,atravessasse,atravessar,Verbo Principal Subjuntivo Imperfeito Terceira...,1
6817,backyardgans,backyardgans,Nome Própio Pessoa,1
6843,bandeirantes,bandeirantes,Nome Própio Organização,1
6862,barraquinhas,barraca,Nome Comun Feminino Plural,1
6865,barriguinhas,barriga,Nome Comun Feminino Plural,1
6926,bichopreguiça,bichopreguiça,Nome Comun Feminino Singular,1
6986,bonecojoaquim,bonecojoaquim,Nome Própio Pessoa,1
7035,brasileiríssima,brasileiro,Adjetivo Qualificativo Feminino Singular,1
7107,cabeleireira,cabeleireiro,Nome Comun Feminino Singular,1
7108,cabeleireiro,cabeleireiro,Nome Comun Masculino Singular,1
7122,cachoeirinha,cachoeirinha,Nome Comun Feminino Singular,1
7192,característica,característica,Nome Comun Feminino Singular,1
7283,chacoalhadinha,chacoalhadinha,Nome Própio Pessoa,1
7300,chapeuzinhovermelho,chapeuzinhovermelho,Nome Própio Pessoa,1
7301,chapeuzinhovermelho,chapeuzinhovermelho,Nome Própio Pessoa,1
7414,coincidentes,coincidente,Adjetivo Qualificativo Comum Plural,1
7479,complicadinho,complicadinho,Verbo Principal Particípio Singular Masculino,1
7508,confortáveis,confortável,Adjetivo Qualificativo Comum Plural,1
7523,consentração,consentração,Nome Comun Feminino Singular,1
7639,cuidadíssimo,cuidado,Adjetivo Qualificativo Superlativo Masculino S...,1
7695,definitivamente,definitivamente,Advérbio Geral,1
7726,desaparafusar,desaparafusar,Verbo Principal Infinitivo,1
7727,desaparecendo,desaparecer,Verbo Principal Gerúndio,1
7728,desapareceram,desaparecer,Verbo Principal Indicativo Passado Terceira Pe...,1
7735,descaradamente,descaradamente,Advérbio Geral,1
7736,descarregada,descarregado,Verbo Principal Particípio Singular Feminino,1
7737,descarreguei,descarregar,Verbo Principal Indicativo Passado Primeira Pe...,1
7747,desconfiança,desconfiança,Nome Comun Feminino Singular,1
7749,descongelado,descongelar,Verbo Principal Particípio Singular Masculino,1
7751,desconhecido,desconhecer,Verbo Principal Particípio Singular Masculino,1
7752,desconsolada,desconsolar,Verbo Principal Particípio Singular Feminino,1
7768,desencaixado,desencaixar,Verbo Principal Particípio Singular Masculino,1
7773,desenganchou,desenganchar,Verbo Principal Indicativo Passado Terceira Pe...,1
7776,desenhozinho,desenho,Nome Comun Masculino Singular,1
7795,desobedecendo,desobedecer,Verbo Principal Gerúndio,1
7798,despedaçadinho,despedaçadinho,Verbo Principal Particípio Singular Masculino,1
7804,desprevenido,desprevenir,Verbo Principal Particípio Singular Masculino,1
7822,devargazinho,devargazinho,Nome Comun Masculino Singular,1
7854,dinossaurinhos,dinossaurinhos,Nome Própio Pessoa,1
7880,divagarzinho,divagarzinho,Nome Comun Masculino Singular,1
7892,documentação,documentação,Nome Comun Feminino Singular,1
7998,eletricidade,eletricidade,Nome Comun Feminino Singular,1
8000,eletrodoméstico,eletrodoméstico,Nome Comun Masculino Singular,1
8030,encantamentos,encantamento,Nome Comun Masculino Plural,1
8080,engraçadinho,engraçado,Nome Comun Masculino Singular,1
8110,entrevistador,entrevistador,Nome Comun Masculino Singular,1
8111,entrevistadora,entrevistador,Nome Comun Feminino Singular,1
8128,equilibrista,equilibrista,Nome Comun Comum Singular,1
8136,esbugalhados,esbugalhar,Verbo Principal Particípio Plural Masculino,1
8152,escondidinhas,escondido,Adjetivo Qualificativo Diminutivo Feminino Plural,1
8153,escondidinho,escondido,Adjetivo Qualificativo Diminutivo Masculino Si...,1
8156,escorregando,escorregar,Verbo Principal Gerúndio,1
8157,escorregasse,escorregar,Verbo Principal Subjuntivo Imperfeito Terceira...,1
8186,espaçodavila,espaçodavila,Nome Própio Pessoa,1
8190,espalhafatoso,espalhafatoso,Adjetivo Qualificativo Masculino Singular,1
8200,espelhomágico,espelhomágico,Nome Própio Outros,1
8242,estacionados,estacionar,Verbo Principal Particípio Plural Masculino,1
8244,estáconseguindo,estáconseguindo,Verbo Principal Gerúndio,1
8245,estadosunidos,estadosunidos,Nome Própio Lugar,1
8246,estadounidos,estadounidos,Nome Própio Lugar,1
8254,estáprocurando,estáprocurando,Verbo Principal Gerúndio,1
8269,estoufazendo,estoufazendo,Verbo Principal Gerúndio,1
8320,experimentada,experimentar,Verbo Principal Particípio Singular Feminino,1
8321,experimentando,experimentar,Verbo Principal Gerúndio,1
8331,extremidades,extremidade,Nome Comun Feminino Plural,1
8378,fazercoceguinha,fazercoceguinha,Adjetivo Qualificativo Feminino Singular,1
8499,formiguinhas,formiga,Nome Comun Feminino Plural,1
8509,fotografados,fotografar,Verbo Principal Particípio Plural Masculino,1
8510,fotografavam,fotografar,Verbo Principal Indicativo Imperfeito Terceira...,1
8756,hipercansada,hipercansada,Verbo Principal Particípio Singular Feminino,1
8757,hipnotizando,hipnotizar,Verbo Principal Gerúndio,1
8781,horrorizadas,horrorizar,Verbo Principal Particípio Plural Feminino,1
8860,impressionou,impressionar,Verbo Principal Indicativo Passado Terceira Pe...,1
8862,improvisação,improvisação,Nome Comun Feminino Singular,1
8880,infelizmente,infelizmente,Advérbio Geral,1
8890,insuportável,insuportável,Adjetivo Qualificativo Comum Singular,1
8899,interpretação,interpretação,Nome Comun Feminino Singular,1
8936,jabuticabeira,jabuticabeira,Nome Própio Pessoa,1
8998,justificações,justificação,Nome Comun Feminino Plural,1
9230,machucadinho,machucadinho,Verbo Principal Particípio Singular Masculino,1
9305,mantanosseratope,mantanosseratope,Nome Comun Masculino Singular,1
9316,maravilhosas,maravilhoso,Adjetivo Qualificativo Feminino Plural,1
9317,maravilhosos,maravilhoso,Nome Comun Masculino Plural,1
9376,medicamentos,medicamento,Nome Comun Masculino Plural,1
9412,meticulosidade,meticulosidade,Nome Comun Feminino Singular,1
9526,movimentação,movimentação,Nome Comun Feminino Singular,1
9527,movimentando,movimentar,Verbo Principal Gerúndio,1
9555,museudehistória,museudehistória,Nome Própio Lugar,1
9661,nossocasamento,nossocasamento,Nome Comun Masculino Singular,1
9856,participante,participante,Nome Própio Organização,1
9857,participantes,participante,Nome Comun Comum Plural,1
9964,perfeitamente,perfeitamente,Advérbio Geral,1
10146,porquinhoespinho,porquinhoespinho,Nome Própio Pessoa,1
10153,portaretrato,portaretrato,Nome Comun Masculino Singular,1
10207,predominando,predominar,Verbo Principal Gerúndio,1
10243,pretendentes,pretendente,Nome Comun Comum Plural,1
10290,provavelmente,provavelmente,Advérbio Geral,1
10298,pterodáctilo,pterodáctilo,Nome Própio Pessoa,1
10357,quebracabeça,quebracabeça,Nome Comun Feminino Singular,1
10363,queconversar,queconversar,Verbo Principal Infinitivo,1
10388,quinquilharia,quinquilharia,Nome Comun Feminino Singular,1
10389,quintaanimada,quintaanimada,Nome Própio Pessoa,1
10406,raciocinando,raciocinar,Verbo Principal Gerúndio,1
10467,redondondinha,redondondinha,Nome Própio Pessoa,1
10470,reencontrálos,reencontrálos,Nome Própio Lugar,1
10504,respondéncia,respondéncia,Nome Comun Feminino Singular,1
10531,rinocerontes,rinoceronte,Nome Comun Masculino Plural,1
10532,riodejaneiro,riodejaneiro,Nome Própio Pessoa,1
10633,salabimbimbim,salabimbimbim,Advérbio Geral,1
10639,sallyscouter,sallyscouter,Nome Própio Pessoa,1
10652,sandalinhachinelo,sandalinhachinelo,Nome Própio Pessoa,1
10657,sãofrancisco,sãofrancisco,Nome Própio Lugar,1
10776,simbolizando,simbolizar,Verbo Principal Gerúndio,1
10781,simplesmente,simplesmente,Advérbio Geral,1
10782,simsalabimsalabimbimbim,simsalabimsalabimbimbim,Advérbio Geral,1
10784,sinsalabinsalabinbinbin,sinsalabinsalabinbinbin,Nome Própio Pessoa,1
10797,sobrehumanas,sobrehumanas,Adjetivo Qualificativo Feminino Plural,1
10803,sofisticados,sofisticar,Verbo Principal Particípio Plural Masculino,1
10832,sorrateiramente,sorrateiramente,Advérbio Geral,1
10879,superdiferente,superdiferente,Adjetivo Qualificativo Comum Singular,1
10881,supergostoso,supergostoso,Nome Própio Pessoa,1
10884,superpoderes,superpoderes,Nome Comun Masculino Plural,1
10885,superpoderosas,superpoderosas,Adjetivo Qualificativo Feminino Plural,1
10930,tapamonstros,tapamonstros,Nome Comun Masculino Plural,1
10945,tartaruguinha,tartaruguinha,Nome Comun Feminino Singular,1
10952,tatatatatata,tatatatatata,Verbo Principal Indicativo Presente Terceira P...,1
10960,tchatchatchatchatchan,tchatchatchatchatchan,Interjeição,1
10961,tchetchetche,tchetchetche,Interjeição,1
10963,tchiatchiatchia,tchiatchiatchia,Interjeição,1
10969,tchiiiiitchiiii,tchiiiiitchiiii,Interjeição,1
10972,tchithcithcitchi,tchithcithcitchi,Interjeição,1
11011,terradonunca,terradonunca,Nome Própio Pessoa,1
11017,tesselopatato,tesselopatato,Nome Comun Masculino Singular,1
11121,trabalhadeira,trabalhador,Adjetivo Qualificativo Feminino Singular,1
11141,transformado,transformar,Verbo Principal Particípio Singular Masculino,1
11142,transformasse,transformar,Verbo Principal Subjuntivo Imperfeito Terceira...,1
11176,triranossaurinho,triranossaurinho,Nome Própio Pessoa,1
11177,trisseranossaurinho,trisseranossaurinho,Nome Própio Pessoa,1
11178,trisserapodes,trisserapodes,Nome Comun Masculino Plural,1
11179,trisseraptor,trisseraptor,Nome Comun Masculino Singular,1
11213,tucutucutucu,tucutucutucu,Nome Própio Pessoa,1
11217,tulutulutulu,tulutulutulu,Nome Própio Pessoa,1
11223,turururururu,turururururu,Nome Própio Pessoa,1
11224,tururutururutururuprupru,tururutururutururuprupru,Nome Própio Pessoa,1
11257,umacoroaparaguilherme,umacoroaparaguilherme,Nome Própio Pessoa,1
11301,vagabundinho,vagabundinho,Nome Própio Pessoa,1
11311,vamosbrincar,vamosbrincar,Verbo Principal Infinitivo,1
11441,vovóvamosfazer,vovóvamosfazer,Verbo Principal Infinitivo,1
11430,voluntariamente,voluntariamente,Advérbio Geral,1

In [40]:
print(df.shape)

(10630, 8)

In [41]:
df.loc[
    [786, 2487, 3186, 2968, 3460, 4546, 6103, 10357, 4249, 7523],
    ["PALAVRA", "LEMA", "CATMORF", "FREQ"]
]

,PALAVRA,LEMA,CATMORF,FREQ
786,quebracabeça,quebracabeça,Nome Comun Feminino Singular,44
2487,escondeesconde,escondeesconde,Verbo Principal Indicativo Presente Terceira P...,7
3186,porcoespinho,porcoespinho,Nome Própio Pessoa,5
2968,cachorroquente,cachorroquente,Adjetivo Qualificativo Comum Singular,5
3460,escondeesconde,escondeesconde,Verbo Principal Indicativo Presente Terceira P...,4
4546,segundafeira,segundafeira,Nome Comun Feminino Singular,3
6103,segundafeira,segundafeira,Nome Comun Feminino Singular,2
10357,quebracabeça,quebracabeça,Nome Comun Feminino Singular,1
4249,inteligéncia,inteligéncia,Nome Comun Feminino Singular,3
7523,consentração,consentração,Nome Comun Feminino Singular,1

In [42]:
correcoes = {
    "quebracabeça": "quebra-cabeça",
    "escondeesconde": "esconde-esconde",
    "porcoespinho": "porco-espinho",
    "cachorroquente": "cachorro-quente",
    "segundafeira": "segunda-feira",
    "inteligéncia": "inteligência",
    "consentração": "concentração"
}

for palavra_antiga, palavra_corrigida in correcoes.items():
    df.loc[df["PALAVRA"] == palavra_antiga, "PALAVRA"] = palavra_corrigida
    df.loc[df["LEMA"] == palavra_antiga, "LEMA"] = palavra_corrigida

In [43]:
df.loc[
    df["PALAVRA"].isin(correcoes.values()),
    ["PALAVRA", "LEMA", "CATMORF", "FREQ"]
].sort_values(by="PALAVRA")

,PALAVRA,LEMA,CATMORF,FREQ
2968,cachorro-quente,cachorro-quente,Adjetivo Qualificativo Comum Singular,5
7523,concentração,concentração,Nome Comun Feminino Singular,1
2487,esconde-esconde,esconde-esconde,Verbo Principal Indicativo Presente Terceira P...,7
3460,esconde-esconde,esconde-esconde,Verbo Principal Indicativo Presente Terceira P...,4
4249,inteligência,inteligência,Nome Comun Feminino Singular,3
3186,porco-espinho,porco-espinho,Nome Própio Pessoa,5
786,quebra-cabeça,quebra-cabeça,Nome Comun Feminino Singular,44
10357,quebra-cabeça,quebra-cabeça,Nome Comun Feminino Singular,1
4546,segunda-feira,segunda-feira,Nome Comun Feminino Singular,3
6103,segunda-feira,segunda-feira,Nome Comun Feminino Singular,2

In [45]:
possiveis_concatenadas = df[
    df["PALAVRA"].str.len() >= 12
].sort_values(by="FREQ", ascending=False)

In [46]:
pd.set_option("display.max_rows", None)

possiveis_concatenadas[
    ["PALAVRA", "LEMA", "CATMORF", "FREQ"]
]

,PALAVRA,LEMA,CATMORF,FREQ
276,pequenininho,pequenininho,Nome Comun Masculino Singular,159
497,pequenininha,pequenininho,Nome Comun Feminino Singular,78
786,quebra-cabeça,quebra-cabeça,Nome Comun Feminino Singular,44
974,interessante,interessante,Adjetivo Qualificativo Comum Singular,33
1133,devagarzinho,devagarzinho,Nome Comun Masculino Singular,26
1191,brinquedinho,brinquedinho,Nome Própio Pessoa,24
1240,tiranossauro,tiranossauro,Nome Comun Masculino Singular,23
1985,brincadeirinha,brincadeira,Nome Comun Feminino Singular,10
1974,atrapalhando,atrapalhar,Verbo Principal Gerúndio,10
2010,dinossaurinho,dinossaurinho,Nome Própio Pessoa,10
2117,brinquedoteca,brinquedoteca,Nome Própio Pessoa,9
2373,questionando,questionar,Verbo Principal Gerúndio,8
2305,estegossauro,estegossauro,Nome Comun Masculino Singular,8
2517,investigação,investigação,Nome Comun Feminino Singular,7
2487,esconde-esconde,esconde-esconde,Verbo Principal Indicativo Presente Terceira P...,7
2885,supermercado,supermercado,Nome Comun Masculino Singular,6
2671,brinquedinhos,brinquedinhos,Adjetivo Qualificativo Masculino Plural,6
2893,telontossauro,telontossauro,Nome Comun Masculino Singular,6
2968,cachorro-quente,cachorro-quente,Adjetivo Qualificativo Comum Singular,5
3186,porco-espinho,porco-espinho,Nome Própio Pessoa,5
3169,pequenininhas,pequenininho,Nome Comun Feminino Plural,5
3449,encantamento,encantamento,Nome Comun Masculino Singular,4
3547,lembrancinha,lembrancinha,Adjetivo Qualificativo Feminino Singular,4
3458,entrevistadora,entrevistador,Nome Comun Feminino Singular,4
3460,esconde-esconde,esconde-esconde,Verbo Principal Indicativo Presente Terceira P...,4
3634,pequenasereia,pequenasereia,Nome Própio Pessoa,4
4546,segunda-feira,segunda-feira,Nome Comun Feminino Singular,3
4624,tridimensional,tridimensional,Adjetivo Qualificativo Comum Singular,3
4577,superpoderosas,superpoderosas,Adjetivo Qualificativo Feminino Plural,3
4599,tiranossaurinho,tiranossaurinho,Nome Própio Pessoa,3
3923,brincadeiras,brincadeira,Nome Comun Feminino Plural,3
4013,cocócocócocócocócocó,cocócocócocócocócocó,Nome Comun Feminino Singular,3
4239,impressionada,impressionar,Verbo Principal Particípio Singular Feminino,3
4240,impressionante,impressionante,Adjetivo Qualificativo Comum Singular,3
4249,inteligência,inteligência,Nome Comun Feminino Singular,3
4250,interrompendo,interromper,Verbo Principal Gerúndio,3
4320,macarrãozinho,macarrão,Nome Comun Masculino Singular,3
4377,museudehistórianatural,museudehistórianatural,Nome Própio Lugar,3
4449,pequenininhos,pequenininho,Nome Comun Masculino Plural,3
4461,piperanodonte,piperanodonte,Nome Própio Pessoa,3
4655,velociraptor,velociraptor,Nome Comun Masculino Singular,3
4560,soldadinhodechumbo,soldadinhodechumbo,Nome Própio Pessoa,3
6245,travesseirinho,travesseiro,Nome Comun Masculino Singular,2
4712,adamaeovagabundo,adamaeovagabundo,Nome Comun Masculino Singular,2
4745,alfabetizada,alemie,Nome Comun Feminino Singular,2
4775,antecipadamente,ant,Nome Própio Pessoa,2
4893,borboletinha,borboletinha,Verbo Principal Indicativo Imperfeito Terceira...,2
4949,caranguejohermitão,caranguejohermitão,Nome Própio Pessoa,2
4955,carneirinhofelpudo,carneirinhofelpudo,Advérbio Geral,2
5051,completamente,completamente,Advérbio Geral,2
5087,coraçãozinho,coração,Nome Comun Masculino Singular,2
5137,departamento,departamento,Nome Comun Masculino Singular,2
5153,desenrolando,desenrolar,Verbo Principal Gerúndio,2
5224,elefantezinho,elefante,Nome Comun Masculino Singular,2
5226,eletrodomésticos,eletrodomésticos,Adjetivo Qualificativo Masculino Plural,2
5244,endireitando,endireitar,Verbo Principal Gerúndio,2
5249,engatinhando,engatinhar,Verbo Principal Gerúndio,2
5261,envergonhada,envergonhar,Verbo Principal Particípio Singular Feminino,2
5273,escondidinha,escondido,Adjetivo Qualificativo Diminutivo Feminino Sin...,2
5274,escorregador,escorregador,Nome Comun Masculino Singular,2
5302,estáchorando,estáchorando,Verbo Principal Gerúndio,2
5303,estádormindo,estádormindo,Verbo Principal Gerúndio,2
5304,estadosunidos,estadosunidos,Nome Própio Lugar,2
5315,estremilique,estremilique,Nome Própio Lugar,2
5328,experimentar,experimentar,Verbo Principal Infinitivo,2
5455,grilofalante,grilofalante,Nome Própio Pessoa,2
5530,investigator,investigator,Nome Comun Masculino Singular,2
5786,ornitorrinco,ornitorrinco,Nome Comun Masculino Singular,2
5804,papelhigiénico,papelhigiénico,Adjetivo Qualificativo Masculino Singular,2
5811,participando,participar,Verbo Principal Gerúndio,2
5812,participantes,participante,Nome Comun Comum Plural,2
5844,pequeniníssima,pequenino,Adjetivo Qualificativo Feminino Singular,2
5956,proprietário,proprietário,Nome Comun Masculino Singular,2
6051,riodejaneiro,riodejaneiro,Nome Própio Pessoa,2
6103,segunda-feira,segunda-feira,Nome Comun Feminino Singular,2
6144,sombrancelha,sombrancelha,Nome Própio Pessoa,2
6145,sombrancelhas,sombrancelhas,Nome Própio Pessoa,2
6278,universidade,universidade,Nome Comun Feminino Singular,2
6571,americanizado,amendoim,Nome Comun Masculino Plural,1
6643,apresentação,apresentação,Nome Comun Feminino Singular,1
6644,apresentador,apresentador,Nome Comun Masculino Singular,1
6645,apresentadora,apresentador,Nome Comun Feminino Singular,1
6692,arranjaremos,arranjar,Verbo Principal Indicativo Futuro Primeira Pes...,1
6699,arrebentando,arrebentar,Verbo Principal Gerúndio,1
6703,arrumadinhas,arrumado,Adjetivo Qualificativo Diminutivo Feminino Plural,1
6704,arrumadinhos,arrumado,Adjetivo Qualificativo Diminutivo Masculino Pl...,1
6739,astronómicas,astronómico,Adjetivo Qualificativo Feminino Plural,1
6756,atravessasse,atravessar,Verbo Principal Subjuntivo Imperfeito Terceira...,1
6817,backyardgans,backyardgans,Nome Própio Pessoa,1
6843,bandeirantes,bandeirantes,Nome Própio Organização,1
6862,barraquinhas,barraca,Nome Comun Feminino Plural,1
6865,barriguinhas,barriga,Nome Comun Feminino Plural,1
6926,bichopreguiça,bichopreguiça,Nome Comun Feminino Singular,1
6986,bonecojoaquim,bonecojoaquim,Nome Própio Pessoa,1
7035,brasileiríssima,brasileiro,Adjetivo Qualificativo Feminino Singular,1
7107,cabeleireira,cabeleireiro,Nome Comun Feminino Singular,1
7108,cabeleireiro,cabeleireiro,Nome Comun Masculino Singular,1
7122,cachoeirinha,cachoeirinha,Nome Comun Feminino Singular,1
7192,característica,característica,Nome Comun Feminino Singular,1
7283,chacoalhadinha,chacoalhadinha,Nome Própio Pessoa,1
7300,chapeuzinhovermelho,chapeuzinhovermelho,Nome Própio Pessoa,1
7301,chapeuzinhovermelho,chapeuzinhovermelho,Nome Própio Pessoa,1
7414,coincidentes,coincidente,Adjetivo Qualificativo Comum Plural,1
7479,complicadinho,complicadinho,Verbo Principal Particípio Singular Masculino,1
7508,confortáveis,confortável,Adjetivo Qualificativo Comum Plural,1
7523,concentração,concentração,Nome Comun Feminino Singular,1
7639,cuidadíssimo,cuidado,Adjetivo Qualificativo Superlativo Masculino S...,1
7695,definitivamente,definitivamente,Advérbio Geral,1
7726,desaparafusar,desaparafusar,Verbo Principal Infinitivo,1
7727,desaparecendo,desaparecer,Verbo Principal Gerúndio,1
7728,desapareceram,desaparecer,Verbo Principal Indicativo Passado Terceira Pe...,1
7735,descaradamente,descaradamente,Advérbio Geral,1
7736,descarregada,descarregado,Verbo Principal Particípio Singular Feminino,1
7737,descarreguei,descarregar,Verbo Principal Indicativo Passado Primeira Pe...,1
7747,desconfiança,desconfiança,Nome Comun Feminino Singular,1
7749,descongelado,descongelar,Verbo Principal Particípio Singular Masculino,1
7751,desconhecido,desconhecer,Verbo Principal Particípio Singular Masculino,1
7752,desconsolada,desconsolar,Verbo Principal Particípio Singular Feminino,1
7768,desencaixado,desencaixar,Verbo Principal Particípio Singular Masculino,1
7773,desenganchou,desenganchar,Verbo Principal Indicativo Passado Terceira Pe...,1
7776,desenhozinho,desenho,Nome Comun Masculino Singular,1
7795,desobedecendo,desobedecer,Verbo Principal Gerúndio,1
7798,despedaçadinho,despedaçadinho,Verbo Principal Particípio Singular Masculino,1
7804,desprevenido,desprevenir,Verbo Principal Particípio Singular Masculino,1
7822,devargazinho,devargazinho,Nome Comun Masculino Singular,1
7854,dinossaurinhos,dinossaurinhos,Nome Própio Pessoa,1
7880,divagarzinho,divagarzinho,Nome Comun Masculino Singular,1
7892,documentação,documentação,Nome Comun Feminino Singular,1
7998,eletricidade,eletricidade,Nome Comun Feminino Singular,1
8000,eletrodoméstico,eletrodoméstico,Nome Comun Masculino Singular,1
8030,encantamentos,encantamento,Nome Comun Masculino Plural,1
8080,engraçadinho,engraçado,Nome Comun Masculino Singular,1
8110,entrevistador,entrevistador,Nome Comun Masculino Singular,1
8111,entrevistadora,entrevistador,Nome Comun Feminino Singular,1
8128,equilibrista,equilibrista,Nome Comun Comum Singular,1
8136,esbugalhados,esbugalhar,Verbo Principal Particípio Plural Masculino,1
8152,escondidinhas,escondido,Adjetivo Qualificativo Diminutivo Feminino Plural,1
8153,escondidinho,escondido,Adjetivo Qualificativo Diminutivo Masculino Si...,1
8156,escorregando,escorregar,Verbo Principal Gerúndio,1
8157,escorregasse,escorregar,Verbo Principal Subjuntivo Imperfeito Terceira...,1
8186,espaçodavila,espaçodavila,Nome Própio Pessoa,1
8190,espalhafatoso,espalhafatoso,Adjetivo Qualificativo Masculino Singular,1
8200,espelhomágico,espelhomágico,Nome Própio Outros,1
8242,estacionados,estacionar,Verbo Principal Particípio Plural Masculino,1
8244,estáconseguindo,estáconseguindo,Verbo Principal Gerúndio,1
8245,estadosunidos,estadosunidos,Nome Própio Lugar,1
8246,estadounidos,estadounidos,Nome Própio Lugar,1
8254,estáprocurando,estáprocurando,Verbo Principal Gerúndio,1
8269,estoufazendo,estoufazendo,Verbo Principal Gerúndio,1
8320,experimentada,experimentar,Verbo Principal Particípio Singular Feminino,1
8321,experimentando,experimentar,Verbo Principal Gerúndio,1
8331,extremidades,extremidade,Nome Comun Feminino Plural,1
8378,fazercoceguinha,fazercoceguinha,Adjetivo Qualificativo Feminino Singular,1
8499,formiguinhas,formiga,Nome Comun Feminino Plural,1
8509,fotografados,fotografar,Verbo Principal Particípio Plural Masculino,1
8510,fotografavam,fotografar,Verbo Principal Indicativo Imperfeito Terceira...,1
8756,hipercansada,hipercansada,Verbo Principal Particípio Singular Feminino,1
8757,hipnotizando,hipnotizar,Verbo Principal Gerúndio,1
8781,horrorizadas,horrorizar,Verbo Principal Particípio Plural Feminino,1
8860,impressionou,impressionar,Verbo Principal Indicativo Passado Terceira Pe...,1
8862,improvisação,improvisação,Nome Comun Feminino Singular,1
8880,infelizmente,infelizmente,Advérbio Geral,1
8890,insuportável,insuportável,Adjetivo Qualificativo Comum Singular,1
8899,interpretação,interpretação,Nome Comun Feminino Singular,1
8936,jabuticabeira,jabuticabeira,Nome Própio Pessoa,1
8998,justificações,justificação,Nome Comun Feminino Plural,1
9230,machucadinho,machucadinho,Verbo Principal Particípio Singular Masculino,1
9305,mantanosseratope,mantanosseratope,Nome Comun Masculino Singular,1
9316,maravilhosas,maravilhoso,Adjetivo Qualificativo Feminino Plural,1
9317,maravilhosos,maravilhoso,Nome Comun Masculino Plural,1
9376,medicamentos,medicamento,Nome Comun Masculino Plural,1
9412,meticulosidade,meticulosidade,Nome Comun Feminino Singular,1
9526,movimentação,movimentação,Nome Comun Feminino Singular,1
9527,movimentando,movimentar,Verbo Principal Gerúndio,1
9555,museudehistória,museudehistória,Nome Própio Lugar,1
9661,nossocasamento,nossocasamento,Nome Comun Masculino Singular,1
9856,participante,participante,Nome Própio Organização,1
9857,participantes,participante,Nome Comun Comum Plural,1
9964,perfeitamente,perfeitamente,Advérbio Geral,1
10146,porquinhoespinho,porquinhoespinho,Nome Própio Pessoa,1
10153,portaretrato,portaretrato,Nome Comun Masculino Singular,1
10207,predominando,predominar,Verbo Principal Gerúndio,1
10243,pretendentes,pretendente,Nome Comun Comum Plural,1
10290,provavelmente,provavelmente,Advérbio Geral,1
10298,pterodáctilo,pterodáctilo,Nome Própio Pessoa,1
10357,quebra-cabeça,quebra-cabeça,Nome Comun Feminino Singular,1
10363,queconversar,queconversar,Verbo Principal Infinitivo,1
10388,quinquilharia,quinquilharia,Nome Comun Feminino Singular,1
10389,quintaanimada,quintaanimada,Nome Própio Pessoa,1
10406,raciocinando,raciocinar,Verbo Principal Gerúndio,1
10467,redondondinha,redondondinha,Nome Própio Pessoa,1
10470,reencontrálos,reencontrálos,Nome Própio Lugar,1
10504,respondéncia,respondéncia,Nome Comun Feminino Singular,1
10531,rinocerontes,rinoceronte,Nome Comun Masculino Plural,1
10532,riodejaneiro,riodejaneiro,Nome Própio Pessoa,1
10633,salabimbimbim,salabimbimbim,Advérbio Geral,1
10639,sallyscouter,sallyscouter,Nome Própio Pessoa,1
10652,sandalinhachinelo,sandalinhachinelo,Nome Própio Pessoa,1
10657,sãofrancisco,sãofrancisco,Nome Própio Lugar,1
10776,simbolizando,simbolizar,Verbo Principal Gerúndio,1
10781,simplesmente,simplesmente,Advérbio Geral,1
10782,simsalabimsalabimbimbim,simsalabimsalabimbimbim,Advérbio Geral,1
10784,sinsalabinsalabinbinbin,sinsalabinsalabinbinbin,Nome Própio Pessoa,1
10797,sobrehumanas,sobrehumanas,Adjetivo Qualificativo Feminino Plural,1
10803,sofisticados,sofisticar,Verbo Principal Particípio Plural Masculino,1
10832,sorrateiramente,sorrateiramente,Advérbio Geral,1
10879,superdiferente,superdiferente,Adjetivo Qualificativo Comum Singular,1
10881,supergostoso,supergostoso,Nome Própio Pessoa,1
10884,superpoderes,superpoderes,Nome Comun Masculino Plural,1
10885,superpoderosas,superpoderosas,Adjetivo Qualificativo Feminino Plural,1
10930,tapamonstros,tapamonstros,Nome Comun Masculino Plural,1
10945,tartaruguinha,tartaruguinha,Nome Comun Feminino Singular,1
10952,tatatatatata,tatatatatata,Verbo Principal Indicativo Presente Terceira P...,1
10960,tchatchatchatchatchan,tchatchatchatchatchan,Interjeição,1
10961,tchetchetche,tchetchetche,Interjeição,1
10963,tchiatchiatchia,tchiatchiatchia,Interjeição,1
10969,tchiiiiitchiiii,tchiiiiitchiiii,Interjeição,1
10972,tchithcithcitchi,tchithcithcitchi,Interjeição,1
11011,terradonunca,terradonunca,Nome Própio Pessoa,1
11017,tesselopatato,tesselopatato,Nome Comun Masculino Singular,1
11121,trabalhadeira,trabalhador,Adjetivo Qualificativo Feminino Singular,1
11141,transformado,transformar,Verbo Principal Particípio Singular Masculino,1
11142,transformasse,transformar,Verbo Principal Subjuntivo Imperfeito Terceira...,1
11176,triranossaurinho,triranossaurinho,Nome Própio Pessoa,1
11177,trisseranossaurinho,trisseranossaurinho,Nome Própio Pessoa,1
11178,trisserapodes,trisserapodes,Nome Comun Masculino Plural,1
11179,trisseraptor,trisseraptor,Nome Comun Masculino Singular,1
11213,tucutucutucu,tucutucutucu,Nome Própio Pessoa,1
11217,tulutulutulu,tulutulutulu,Nome Própio Pessoa,1
11223,turururururu,turururururu,Nome Própio Pessoa,1
11224,tururutururutururuprupru,tururutururutururuprupru,Nome Própio Pessoa,1
11257,umacoroaparaguilherme,umacoroaparaguilherme,Nome Própio Pessoa,1
11301,vagabundinho,vagabundinho,Nome Própio Pessoa,1
11311,vamosbrincar,vamosbrincar,Verbo Principal Infinitivo,1
11441,vovóvamosfazer,vovóvamosfazer,Verbo Principal Infinitivo,1
11430,voluntariamente,voluntariamente,Advérbio Geral,1

## Salvamento do estado atual

In [ ]:
# salva a base depois das remoções e correções desta etapa
df.to_excel("Corpus_SANTOS_TONI_FDC_tratado_sem_repeticoes.xlsx", index=False)
print("Base salva:", df.shape)

In [47]:
df.shape[0]

10630

In [48]:
df["PALAVRA"].nunique()

9864

In [49]:
df = df.sort_values(
    by=["PALAVRA", "FREQ"],
    ascending=[True, False]
)

df = df.drop_duplicates(
    subset="PALAVRA",
    keep="first"
).copy()

In [50]:
print("Total de registros:", len(df))
print("Palavras diferentes:", df["PALAVRA"].nunique())

Total de registros: 9864
Palavras diferentes: 9864

In [51]:
df.to_excel(
    "Corpus_SANTOS_TONI_FDC_tratado_sem_repeticoes.xlsx",
    index=False
)